### ISSUE TITLE
Could not load SSL library

### ISSUE THREAD

**Issue by Henrik9691** [AliDehbansiahkarbon/ChatGPTWizard#12]
When running ChatGPT on RadStudio 11.3 installed by GetManager within Delphi 11.3 i'm getting this response 'Could not load SSL library' when clicking on the Ask button.

What ssl libarary needs to be installed?

ChatGPT API key are set in steeings.

The Behavior:
Open ChatGPT on the Menu bar of Delphi
Select Ask ChatGPT
Write a question or just use the template 'Create a class to make a Zip file in Delphi.'
Click 'Ask'
Response : 'Could not load SSL library'

<img width="461" alt="2023-03-30_18-56-42" src="https://user-images.githubusercontent.com/113128813/228910026-91583501-0d72-4637-bb11-de6421b9db97.png">
<img width="500" alt="2023-03-30_18-57-42" src="https://user-images.githubusercontent.com/113128813/228910163-2ae14409-d90c-47c8-8d60-83927760906d.png">
<img width="701" alt="2023-03-30_18-58-30" src="https://user-images.githubusercontent.com/113128813/228910523-bb146db8-d9e1-4698-9648-e9b8aa2e88f3.png">

**Comment by flydev-fr** [comment]
I had the same issue, [reading the doc](https://github.com/AliDehbansiahkarbon/ChatGPTWizard#issues-with-ssl) solved the issue.

**Comment by AliDehbansiahkarbon** [comment]
@Henrik9691 Read the ReadMe, please! ([This section](https://github.com/AliDehbansiahkarbon/ChatGPTWizard#issues-with-ssl:~:text=This%20issue%20can,more%20useful%20anyways.))
