### ISSUE TITLE
Invalid pointer operation

### ISSUE THREAD

**Issue by ice-product96** [AliDehbansiahkarbon/ChatGPTWizard#13]
I installed delphi 10.3 and delphi 11.2, inserted the key and made a request and received a response 404 Not Found.
then I clicked load default values, inserted the key again and clicked save.
depending on the choice of model, the message changes, for example, if you choose gpt-3.5-turbo, the response will already be HTTP/1.1 404 Not Found

**Comment by AliDehbansiahkarbon** [comment]
Fixed.
About the mode "gpt-3.5-turbo" consider this is not a code completion model, it's just a chat model which is not suitable for code in my opinion, but if you insist on using that you have to use a different base URL(a warning has been added in this regard to avoid mistakes) .
