### ISSUE TITLE
After last update it stops working

### ISSUE THREAD

**Issue by instigator21** [AliDehbansiahkarbon/ChatGPTWizard#14]
HTTP/1.1 404 Not Foun is answer for the Asking. 

**To Reproduce**
1. Setup settings for gpt-3.5-turbo 
![image](https://user-images.githubusercontent.com/1425866/229205181-bd5c57af-19eb-4af5-9a3d-2a9a6fc15e57.png)

Go to the Dockable form, set the question and press Ask
![image](https://user-images.githubusercontent.com/1425866/229205374-3b53a725-a138-4f17-921b-592ffe330c9c.png)

**Comment by AliDehbansiahkarbon** [comment]
Fixed.
About the model "gpt-3.5-turbo", consider this is not a code completion model, it's just a chat model which is not suitable for code in my opinion, but if you insist on using that you have to use a different base URL(a warning has been added in this regard to avoid mistakes).
Set it again in the setting after updating to the latest version.
- Default ChatGPT base URL = https://api.openai.com/v1/completions;
- 3.5Turbo base URL = https://api.openai.com/v1/chat/completions;
