### ISSUE TITLE
Invalid pointer operation

### ISSUE THREAD

**Issue by Jazzic** [AliDehbansiahkarbon/ChatGPTWizard#15]
**Describe the bug**
"Invalid pointer operation" is written in the editor. No response in the Answer box in the ChatGPT dialog window.

**To Reproduce**
1. write "cpt:Create a full unit in Delphi including a class to create an XML file.:cpt" in the editor window
2. Press CTRL+ALT+SHIFT+A
3. "Invalid pointer operation" is written in the editor.

In the ChatGPT dialog, there is no response in the Answer box when asking a question.

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Windows 11 Pro Version 22H2
 - Chrome Version 111.0.5563.147
 - Delphi 11.2 Version 28.0.46141.0937

**Smartphone (please complete the following information):**

**Additional context**

**Comment by AliDehbansiahkarbon** [comment]
Fixed.
