### ISSUE TITLE
Incorrect display of Russian characters.

### ISSUE THREAD

**Issue by ice-product96** [AliDehbansiahkarbon/ChatGPTWizard#16]
Hello, can you correct the encoding?
![изображение](https://user-images.githubusercontent.com/68703689/229477816-d7580bcd-48f8-401f-b774-c0e47647ebe3.png)

**Comment by AliDehbansiahkarbon** [comment]
Hi, this issue has been fixed for Russian and all other languages.

![image](https://user-images.githubusercontent.com/5601608/230425768-6f6c884e-0bd2-4d90-ab76-df2d83effa7b.png)
