### ISSUE TITLE
Every time I Build/Compile/Install ChatGPTWizard old installation menu remain there.

### ISSUE THREAD

**Issue by CiceroBillo** [AliDehbansiahkarbon/ChatGPTWizard#2]
Every time I Build/Compile/Install ChatGPTWizard old installation menu remain there. It's necessary to Free old ChatGPT menu item and create again.

![image](https://user-images.githubusercontent.com/6755631/216677052-c24903d0-8c74-49b9-afab-e1bf9a0678c9.png)

**Comment by AliDehbansiahkarbon** [comment]
Fixed.
