### ISSUE TITLE
History Database Does Not Exist

### ISSUE THREAD

**Issue by plumothy** [AliDehbansiahkarbon/ChatGPTWizard#23]
Click on the History tab In the Dockable window - produces this error:
![image](https://user-images.githubusercontent.com/18924878/231075045-058c0ef4-e26d-4901-9cc7-caccabcd813e.png)

Note: I have History.sdb in ...\Embarcadero\Studio\22.0\CatalogRepository\ChatGPTWizard-2.0\Resources\DB

Delphi 11.3
Windows 11

**Comment by AliDehbansiahkarbon** [comment]
Well, there is nothing really wrong with the code in this regard and it's not an error, actually, it is a warning message,

It's simply using the FileExists() function, so make sure :
1- The history path is correct, it's a **Directory** path without a trailing backslash, not a full path.
![image](https://user-images.githubusercontent.com/5601608/231089944-cd67aef8-9e9e-4a35-949e-26575dec547d.png)

2- There is no permission problem.
3- The path is not too long.

**Comment by plumothy** [comment]
OK, thanks. When I posted this issue I had History.sdb in the folder specified in the settings (or so I thought).
However, somehow it disappeared - but I have no idea why.
I just grabbed another copy from github and it is working again.
So, it is a bit worrying that a file can just vanish for no apparent reason.
If it happens again I will let you know (but hopefully it was a one-off).
