### ISSUE TITLE
D10.0 compatibility

### ISSUE THREAD

**Issue by Dzyszla** [AliDehbansiahkarbon/ChatGPTWizard#26]
D10.0 don't support flowing property:

```
  LvHttpClient := THTTPClient.Create;
  LvHttpClient.**ConnectionTimeout** := FTimeOut * 1000;
  LvHttpClient.**ResponseTimeout** := (FTimeOut * 1000) * 2;
```

**Errors:**

> [dcc32 Error] UYouChatThread.pas(160): E2003 Undeclared identifier: 'ConnectionTimeout'
> [dcc32 Error] UYouChatThread.pas(161): E2003 Undeclared identifier: 'ResponseTimeout'
> [dcc32 Fatal Error] ChatGptWizard.dpk(59): F2063 Could not compile used unit 'UYouChatThread.pas'

**Comment by AliDehbansiahkarbon** [comment]
Hi, this plug-in just supports from 10.1 Berlin to later versions at this stage.
It's mentioned ([here](https://github.com/AliDehbansiahkarbon/ChatGPTWizard#:~:text=Remarks,and%20later%20versions.)) in ReadMe.
