### ISSUE TITLE
Change theme doesn't effect the dockable form.

### ISSUE THREAD

**Issue by Snglst** [AliDehbansiahkarbon/ChatGPTWizard#28]
**Describe the bug**
Change theme doesn't effect the dockable form and you have to close and open this form to get the new style.

**To Reproduce**
Just open dockable form, docked or not docked doesn't matter, then try to change the style of the IDE.

**Expected behavior**
Real time color change same as other IDE components.

**Screenshots**
![image](https://user-images.githubusercontent.com/128783849/231749733-577b9eca-b784-4e3b-9898-231993e5c82c.png)
![image](https://user-images.githubusercontent.com/128783849/231749838-5aea7b97-50f6-4eb6-afae-2d628f689c52.png)

 - OS: windows 11
 - IDE Alexandria 11.1

**Comment by AliDehbansiahkarbon** [comment]
Fixed.
