### ISSUE TITLE
مشکل فعالسازی در کشور ایران

### ISSUE THREAD

**Issue by rvaladi** [AliDehbansiahkarbon/ChatGPTWizard#3]
با سلام 
ظاهرا شرکت OpenAI به کشور ایران (خط موبایل ایران  )خدمات و کد فعالسازی نمی دهد ؟
برای این موضوع راهکاری دارید؟
با تشکر

**Comment by AliDehbansiahkarbon** [comment]
برای ساخت اکانت احتمالاً میتوانید شماره تلفن مجازی تهیه کنید و در هنگام استفاده از پلاگین نیز باید آی پی خود را تغییر دهید.
برای تهیه ی شماره ی مجازی سرویس های بسیاری وجود دارد برای نمونه وارد https://numberland.ir سایت شوید و گزینه ی OpenAI را انتخاب کنید و مراحل را طی بفرمایید.
![image](https://user-images.githubusercontent.com/5601608/216821037-1ad448af-c625-4939-9a59-5fdac31eeb9e.png)

**Comment by AliDehbansiahkarbon** [comment]
روش دوم استفاده از سایت ایرانیکارت (https://www.iranicard.ir) هست، بعد از ثبت نام وارد منوی سایت شده گزینه ی سرویس ها و بعد گزینه ی دیگر سرویس ها را انتخاب کنید و در این مرحله گزینه ی "شماره ی مجازی مخصوص Open AI" را انتخاب کنید، با این شماره باید بتوانید اکانت خود را فعال سازی نمایید.

**Comment by AliDehbansiahkarbon** [comment]
امکان استفاده از پروکسی هم اضافه شد!
