### ISSUE TITLE
History

### ISSUE THREAD

**Issue by limelect** [AliDehbansiahkarbon/ChatGPTWizard#31]
D10.2.3
History does not work
Search chate
then go to history. Nothing.
when searching writesonic search goes to chategpt
How do you get to search predefined questions?

Furthermore when copying each line adds a line feed which is not needed
Also, copying did it twice !!!! may chat send it twice?

.

**Comment by AliDehbansiahkarbon** [comment]
Hi,
Fixed some bugs regarding the History, try the latest, please.

**### Using the latest version:** 
- "History does not work": History works fine.
- "When searching writesonic search goes to chategpt" : consider keywords will be searched in questions, not in answers.
- "How do you get to search predefined questions?" :  predefined ones will be logged like other questions you just need to search the right keywords.
- "Furthermore when copying each line adds a line feed which is not needed
Also, copying did it twice !!!! may chat send it twice?" : I couldn't reproduce this one, KeyPreview is enabled on the dockable form and it should handle keyboard events, use the latest version and if the problem remains then provide more info to reproduce it at my end, please. (maybe a recorded video?).

**Comment by limelect** [comment]
1. Search
2.Dbl line feed in the editor
3.No history

![Screenshot - 18_04_2023 , 10_02_54](https://user-images.githubusercontent.com/4199131/232698006-8492e763-a9fb-43fb-94f4-efd419866a13.jpg)
![Screenshot - 18_04_2023 , 10_03_31](https://user-images.githubusercontent.com/4199131/232698020-128770d3-f791-4637-8e4e-42603ea0fce8.jpg)
![Screenshot - 18_04_2023 , 10_03_53](https://user-images.githubusercontent.com/4199131/232698027-fe611f57-63b1-41c9-b136-c2e0daf620c0.jpg)

**Comment by limelect** [comment]
could not understand your answer
How do you insert a predefine question into the question pan

"How do you get to search predefined questions?" : predefined ones will be logged like other questions you just need to search the right keywords.

**Comment by AliDehbansiahkarbon** [comment]
Did you set the history path and enabled the history in the setting?
The location is a directory path, not a full path.
![image](https://user-images.githubusercontent.com/5601608/232704743-488f4a55-b5bb-4f20-b3ce-f274f40bc06a.png)

**Comment by limelect** [comment]
OK you are right **BUT**
![Screenshot - 18_04_2023 , 10_42_49](https://user-images.githubusercontent.com/4199131/232707927-61355434-aefe-4a52-ba61-95ff31a63f90.jpg)
![Screenshot - 18_04_2023 , 10_43_19](https://user-images.githubusercontent.com/4199131/232707938-8c27157d-ebf8-402a-9e87-7c0227e53891.jpg)

**Comment by limelect** [comment]
May be the initialization of DB is missing 
If NOE EXIST?

**Comment by limelect** [comment]
OK sorry did not read carfully

**Comment by limelect** [comment]
OK new problem is seen in HISTORY

***** WriteSonic *****
Server Certificate Invalid or not presen

**Comment by AliDehbansiahkarbon** [comment]
> OK you are right **BUT** ![Screenshot - 18_04_2023 , 10_42_49](https://user-images.githubusercontent.com/4199131/232707927-61355434-aefe-4a52-ba61-95ff31a63f90.jpg) ![Screenshot - 18_04_2023 , 10_43_19](https://user-images.githubusercontent.com/4199131/232707938-8c27157d-ebf8-402a-9e87-7c0227e53891.jpg)

I have added a single line to avoid this one.
Pull it, please.

**Comment by limelect** [comment]
This problem came about with some other chat projects.
When I used **FPiette** CHAT it did not happen because he used SSL DLL.
I did my own with his way
As a matter of fact, I used 2 projects where one was so lovely with FMX.

![Screenshot - 18_04_2023 , 11_04_38](https://user-images.githubusercontent.com/4199131/232715397-2e3ff747-2286-4a7a-a513-86bb0bc974c4.jpg)

**Comment by AliDehbansiahkarbon** [comment]
> OK new problem is seen in HISTORY
> 
> ***** WriteSonic ***** Server Certificate Invalid or not present

About WriteSonic, this message is coming from their API, try to log in to their website and check your remaining words.


![image](https://user-images.githubusercontent.com/5601608/232716113-231d48cf-dbfc-434b-b2eb-fdb5c703dd03.png)

**Comment by AliDehbansiahkarbon** [comment]
About the secure connection and encryption methods I have to mention that this plug-in is open source and you can change its behavior if you want, but the current method is trying to use the built-in "System.Net" library first which doesn't need SSL libraries, in case there is any problem it will try to use Indy + SSL DLLs as a second method.
Those DLLs are even available in the Resource folder and some tips about them can be found [here](https://github.com/AliDehbansiahkarbon/ChatGPTWizard#:~:text=Issues%20with%20SSL,more%20useful%20anyways.).

**Comment by AliDehbansiahkarbon** [comment]
@birbilis 
An independent application like this FMX-based one that you mentioned don't have any limitation in design and structure, but this plug-in must work inside the IDE and there are some limitations, I will continue to make it better and more flexible as possible but for now, I assume this issue is done, if you faced any other problem please open another issue or try discussion tab here first, we can always turn the discussion to issue as well.

**Comment by limelect** [comment]
Now history is bad again and stopped working
Although i am on chatGPT I get this msg

***** WriteSonic *****
Server Certificate Invalid or not present
so I closed writesonic it did not help.
I closed Delphi it was OK BUT
ONLY FOR ONE MSG !!!.
I deleted the history lines run chat  NOTHIN NO HISTORY

**Comment by AliDehbansiahkarbon** [comment]
Ok.
I'm really going to fix every single problem you faced with this plug-in but I'm not sure about the settings, the environment's other options, permissions, OS, etc.

## Please follow these steps

- Double-check that you are using the latest source.
- Pull the latest code, do right-click on the project, clear, uninstall, build, and install again.
- for Writesonic and Youchat you need to prepare different API keys and make sure it works in Postman first.
- In the end, if the problem remains please reach me on Skype (live:adehban) so I can have a closer look (maybe with AnyDesk or something like that) to fix issues.
