### ISSUE TITLE
Add proxy host and port in the setting page

### ISSUE THREAD

**Issue by pmiscn** [AliDehbansiahkarbon/ChatGPTWizard#4]
Add proxy host and port in the setting page

**Comment by AliDehbansiahkarbon** [comment]
Proxy server option has been added, but I don't have access to a proxy server to test that properly.
So I'm not going to close this issue until you (@pmiscn) or someone else approve that it works well.

**Comment by AliDehbansiahkarbon** [comment]
Has been tested.
