### ISSUE TITLE
Chat Moderation

### ISSUE THREAD

**Issue by liftoff1968** [AliDehbansiahkarbon/ChatGPTWizard#55]
Hi. I have a question or comment regarding the use of the OpenAI API. In the code, the endpoint "https://api.openai.com/v1/chat/completions" is used. In this process, the prompts from the user are passed to the model unfiltered. Although this is unlikely to be the case often when programming, the user can send prompts to the model that violate OpenAI's rules. I could not find any moderation.

Is this assessment correct?

That would be problematic, as OpenAI is very strict about following the rules. They don't ask questions first, they just close the account. In a company with many people, this would not be so nice.

**Comment by AliDehbansiahkarbon** [comment]
Hello,

While it is possible for users to make mistakes while using browsers, mobile apps, or other software, it is ultimately the responsibility of the user. The plugin is designed to act as a bridge between the user's IDE and the OpenAI, making it smarter and faster during the development process. 
It's important to keep in mind that the plugin is intended for programming purposes only, and users should use it accordingly!

**Comment by liftoff1968** [comment]
Thank you for your response. Unfortunately, people make mistakes and/or do foolish things. And sadly, not everyone understands the responsibility that comes with using an API key. In this case, the developers might not even be aware that they are using a key. The OpenAI dev board is full of surprised developers and users whose accounts have been closed. And when it's closed, it's closed.
Maybe you could just mention it again prominently somewhere. Those who need moderation can then build it in themselves. :-)

**Comment by AliDehbansiahkarbon** [comment]
Ok, I will mention that in an appropriate place.
