### ISSUE TITLE
Add option to use a local llm, such as Ollama

### ISSUE THREAD

**Issue by iplayfast** [AliDehbansiahkarbon/ChatGPTWizard#58]
It should be as simple as 
From the users side:
1. install ollama https://ollama.com/ 
2. run ollama to load a model, (eg ollama run llama)

from your code side:
1. update UChatGPTSetting.dfm to include ollama in the list
2. if the settings is set to ollama, then update the edt_Url to 'http://localhost://11434/v1/chat/completions'
4. Allow the user to specify their model or query ollama to see what models are currently present.

**Comment by AliDehbansiahkarbon** [comment]
Hi, an offline solution has been my concern since the beginning, but I was waiting for a simple, powerful,  easy-to-install and use one.
I'm currently playing with https://opencopilot.so.

Still, your suggestion seems promising, probably I will add yours first.
Thank you.
