### ISSUE TITLE
Can ChatGptWizard be  used by a delphi application? 

### ISSUE THREAD

**Issue by bishara2000** [AliDehbansiahkarbon/ChatGPTWizard#61]
Hello Ali
I downloaded and installed your ChatGptWizard in my delphi 11.3 environment. Every thing is fine and I could make my chat very well.
However I have been  struggling very hard to implement this functionality within my delphi application. That will be very nice to combine the power of the ai engine and my application, My students are looking forward for that.
All I need is to be able to execute a function such as the following:
GtpAnswer:=GetGptAnswer(MyQuestion)

I am suscibed to ChatGtp 4.
Please I woukd highly appreciate your assistance with this issue.
Bishara Wakim

**Comment by AliDehbansiahkarbon** [comment]
Hi Bishara,
This plug-in is not meant to do that.
I made a desktop sample, you just need to add your API Key.
Download it here: 
[Simple GPT Desktop.zip](https://github.com/AliDehbansiahkarbon/ChatGPTWizard/files/15068877/Simple.GPT.Desktop.zip)

**Comment by AliDehbansiahkarbon** [comment]
Moreover, there are some rich libraries and components made for Delphi to be used in your application:
[DelphiOpenAI](https://github.com/HemulGM/DelphiOpenAI) 
[RDOpenAI](https://github.com/baumwollschaf/RDOpenAI)
[DelphiChatGPT](https://github.com/geoffsmith82/DelphiChatGPT)

**Comment by bishara2000** [comment]
Than you very much Ali!!
I appreciate your help...
________________________________
