### ISSUE TITLE
Access violation at address XXXXX in module 'ChatGptWizard.bpl'

### ISSUE THREAD

**Issue by asbuka** [AliDehbansiahkarbon/ChatGPTWizard#62]
Problem:

Unit: UChatGptMain.pas -> class procedure TEditNotifierHelper.FormatSource;

Solution:

class procedure TEditNotifierHelper.FormatSource;
var
  LvEditorPopUpMenu: TPopupMenu;
  **LvFormatSource: TMenuItem;**
begin
  LvEditorPopUpMenu := TPopupMenu((BorlandIDEServices as IOTAEditorServices).TopView.GetEditWindow.Form.FindComponent('EditorLocalMenu'));
  if LvEditorPopUpMenu <> nil then
  begin
    **LvFormatSource** := LvEditorPopUpMenu.Items.Find('Format Source');
    if **Assigned(LvFormatSource)** then
      LvFormatSource.Click;
  end;
end;

![2024-05-13 13_16_34-Fehler](https://github.com/AliDehbansiahkarbon/ChatGPTWizard/assets/3490542/ba9e05b5-d0d8-49eb-a27b-c790f0faab08)
![2024-05-13 13_18_26-Setting](https://github.com/AliDehbansiahkarbon/ChatGPTWizard/assets/3490542/be677312-a2d4-467d-a986-76a81f1caf8f)
[ErrorLog.txt](https://github.com/AliDehbansiahkarbon/ChatGPTWizard/files/15293631/ErrorLog.txt)

**Comment by AliDehbansiahkarbon** [comment]
Hi,
I replaced your method with the current one.
Thank you.
