### ISSUE TITLE
History error message

### ISSUE THREAD

**Issue by Spelt** [AliDehbansiahkarbon/ChatGPTWizard#65]
Hi

When I ask a question I get an error: The database file doesn't exist. 

I'm using the version via GetIt in Delphi 12.1.

Hope you can help!

**Comment by AliDehbansiahkarbon** [comment]
Hi, 
There is an empty DB file in this path in the project folder:  Resources\DB\History.sdb
Please make sure the history setting is correctly pointing to this file or you can disable history in the setting form of the wizard.

![image](https://github.com/AliDehbansiahkarbon/ChatGPTWizard/assets/5601608/1f311dd3-8e43-4eb1-9de0-ccbe77e80707)

**Comment by Spelt** [comment]
Thanks. I copied the file and that works.

It would be great if this works out of the box.

**Comment by Spelt** [comment]
I would also be great if there is a separate Ollama setting section.  It has nothing to do with OpenAI.  Anyway thanks!

**Comment by AliDehbansiahkarbon** [comment]
If you uncheck the Enabled checkbox in the History section it should work without any problem.
But I will make some modifications whenever I can.

There is a discussion tab here in this repository, please share your thoughts or ideas there.
