### ISSUE TITLE
Ollama problem

### ISSUE THREAD

**Issue by Spelt** [AliDehbansiahkarbon/ChatGPTWizard#66]
Hi,

When I install Ollama  I can ask question via the prompt and it works. If I enable the checkbox Ollama and add: http://localhost:11434/api/generate and the I ask a question I get:  **Unexpected end of input. (Line: 1 Col: 1**

Hope you can help!

Thanks Edward

**Comment by AliDehbansiahkarbon** [comment]
Did you pull a model for Ollama?
If so which model is it?

![image](https://github.com/AliDehbansiahkarbon/ChatGPTWizard/assets/5601608/e9c6f056-37e4-47c0-9892-bbd81ce892fa)

**Comment by Spelt** [comment]
Thanks that works.

I also managed Ollama to listen from another machine. Default it works with localhost only.
